# Generated by Django 4.0.6 on 2022-07-06 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0006_stock_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('user', 'ticker')},
        ),
    ]
